In [1]:
import pandas as pd
from glob import glob

def get_csv(uri):
    csvs = []
    if "*" in uri:
        all_csv = glob(uri)
        [ csvs.append(pd.read_csv(uri)) for uri in all_csv ]
        return pd.concat(csvs)
    return pd.read_csv(uri)

scenario = "36-1"

In [2]:
labels = get_csv('/media/kmdr7/Seagate/DATASETS/IOT-23/CTU-IoT-Malware-Capture-'+scenario+'/bro/labels.csv')

In [3]:
datasets = get_csv('/media/kmdr7/Seagate/DATASETS/IOT-23/CTU-IoT-Malware-Capture-'+scenario+'/out/*')

In [4]:
labels

,Id,Field,bro field number,Data,Comparator,Label,type,connector
0,1,id.resp_p,4,6667,eq,C&C,Malicious,-
1,2,id.resp_p,4,63798,eq,PartOfAHorizontalPortScan,Malicious,-
2,3,id.resp_p,4,256,eq,PartOfAHorizontalPortScan,Malicious,-
3,4,id.resp_p,4,5376,eq,DDoS,Malicious,-
4,5,id.resp_h,3,123.59.209.185,eq,DDoS,Malicious,-
5,6,id.resp_h,3,71.61.66.148,eq,DDoS,Malicious,-
6,7,id.resp_h,3,74.91.117.248,eq,DDoS,Malicious,-

In [6]:
datasets.head(5)

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Total Fwd Packet,Total Bwd packets,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.1.195-185.244.25.235-41040-80-6,192.168.1.195,41040,185.244.25.235,80,6,21/12/2018 09:50:16 PM,33373221,94,93,...,32,7219146.0,0.0,7219146.0,7219146.0,5.151346e+14,8.922393e+14,1.545404e+15,8.160091e+06,NeedManualLabel
1,192.168.1.195-185.244.25.235-41040-80-6,192.168.1.195,41040,185.244.25.235,80,6,21/12/2018 09:50:50 PM,123180,5,3,...,32,0.0,0.0,0.0,0.0,1.545404e+15,0.000000e+00,1.545404e+15,1.545404e+15,NeedManualLabel
2,192.168.1.195-185.244.25.235-41042-80-6,192.168.1.195,41042,185.244.25.235,80,6,21/12/2018 09:50:50 PM,8519800,98,93,...,32,0.0,0.0,0.0,0.0,1.545404e+15,0.000000e+00,1.545404e+15,1.545404e+15,NeedManualLabel
3,192.168.1.195-185.244.25.235-41044-80-6,192.168.1.195,41044,185.244.25.235,80,6,21/12/2018 09:50:59 PM,999109,66,65,...,32,0.0,0.0,0.0,0.0,1.545404e+15,0.000000e+00,1.545404e+15,1.545404e+15,NeedManualLabel
4,192.168.1.195-185.244.25.235-41046-80-6,192.168.1.195,41046,185.244.25.235,80,6,21/12/2018 09:51:00 PM,4116407,72,69,...,32,0.0,0.0,0.0,0.0,1.545404e+15,0.000000e+00,1.545404e+15,1.545404e+15,NeedManualLabel

In [7]:
malware = datasets[
    (datasets["Dst IP"] == "123.59.209.185") |
    (datasets["Dst IP"] == "71.61.66.148") |
    (datasets["Dst IP"] == "74.91.117.248") |
    (datasets["Dst Port"] == 6667) |
    (datasets["Dst Port"] == 63798) |
    (datasets["Dst IP"] == 256) |
    (datasets["Dst IP"] == 5376)
]
malware.shape

(5147, 84)

In [8]:
benign = datasets.drop(malware.index)
benign.shape

(1488, 84)

In [9]:
malware.to_csv("/media/kmdr7/Seagate/FP/MENTAH/Malware/"+scenario+".csv", index=False)
benign.to_csv("/media/kmdr7/Seagate/FP/MENTAH/Benign/"+scenario+".csv", index=False)