In [1]:
import pandas as pd

In [2]:
dataset = pd.read_excel("/home/kmdr7/Downloads/hasil-export_16.xlsx")

In [3]:
datas = []
bulan = ["januari", "februari", "maret", "april", "mei", "juni", "juli", "agustus", "september", "oktober", "november", "desember"]

In [4]:
provinsi = dataset.iloc[3:37]

In [7]:
years = [2018, 2019, 2020]
ranges = [[1,14], [14,27], [27,40]]
itr_year = 0
for rg in ranges:
    cur_ds = dataset.iloc[3:37, rg[0]:rg[1]-1]
    for idx in range(0, 33):
        itr = 0
        cur_prov = provinsi.iloc[idx][0]
        for data_idx in provinsi.iloc[idx][rg[0]:rg[1]-1]:
            print("insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('"+cur_prov+"', "+str(years[itr_year])+", '"+bulan[itr]+"', "+str(data_idx)+", 'padi');")
            itr+=1
    itr_year+=1

insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Aceh', 2018, 'januari', 2444.25, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Aceh', 2018, 'februari', 1993.7, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Aceh', 2018, 'maret', 1816.75, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Aceh', 2018, 'april', 506.45, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Aceh', 2018, 'mei', 184.5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Aceh', 2018, 'juni', 519.1, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Aceh', 2018, 'juli', 919.38, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Aceh', 2018, 'agustus', 1115.75, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Aceh', 2018, 'september', 782.75, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Aceh', 2018, 'oktober', 461.75, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Aceh', 2018, 'november', 292, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Aceh', 2018, 'desember', 1315.25, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Utara', 2018, 'januari', 988.26, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Utara', 2018, 'februari', 577.2, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Utara', 2018, 'maret', 665.3, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Utara', 2018, 'april', 823.46, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Utara', 2018, 'mei', 924.49, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Utara', 2018, 'juni', 820.75, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Utara', 2018, 'juli', 1022.5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Utara', 2018, 'agustus', 956.6, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Utara', 2018, 'september', 538.4, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Utara', 2018, 'oktober', 526.2, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Utara', 2018, 'november', 593.4, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Utara', 2018, 'desember', 849.1, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Barat', 2018, 'januari', 174.55, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Barat', 2018, 'februari', 191.4, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Barat', 2018, 'maret', 204.9, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Barat', 2018, 'april', 198.25, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Barat', 2018, 'mei', 178, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Barat', 2018, 'juni', 114.1, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Barat', 2018, 'juli', 319.71, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Barat', 2018, 'agustus', 215.45, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Barat', 2018, 'september', 269.1, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Barat', 2018, 'oktober', 563.91, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Barat', 2018, 'november', 398.4, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Barat', 2018, 'desember', 191, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Riau', 2018, 'januari', 243.5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Riau', 2018, 'februari', 80, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Riau', 2018, 'maret', 26.7, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Riau', 2018, 'april', 89.35, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Riau', 2018, 'mei', 166.4, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Riau', 2018, 'juni', 204.25, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Riau', 2018, 'juli', 485.45, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Riau', 2018, 'agustus', 26.3, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Riau', 2018, 'september', 59.6, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Riau', 2018, 'oktober', 183.7, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Riau', 2018, 'november', 553.7, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Riau', 2018, 'desember', 555.75, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jambi', 2018, 'januari', 97.34, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jambi', 2018, 'februari', 131.12, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jambi', 2018, 'maret', 66.17, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jambi', 2018, 'april', 62.92, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jambi', 2018, 'mei', 96.22, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jambi', 2018, 'juni', 0, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jambi', 2018, 'juli', 169.07, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jambi', 2018, 'agustus', 184.96, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jambi', 2018, 'september', 62.35, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jambi', 2018, 'oktober', 75.34, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jambi', 2018, 'november', 89.81, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jambi', 2018, 'desember', 64.57, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Selatan', 2018, 'januari', 3874.42, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Selatan', 2018, 'februari', 2681.7, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Selatan', 2018, 'maret', 1664.01, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Selatan', 2018, 'april', 1315.61, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Selatan', 2018, 'mei', 1698.6, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Selatan', 2018, 'juni', 2197.57, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Selatan', 2018, 'juli', 3267.48, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Selatan', 2018, 'agustus', 808.85, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Selatan', 2018, 'september', 476.09, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Selatan', 2018, 'oktober', 320.03, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Selatan', 2018, 'november', 683.23, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Sumatera Selatan', 2018, 'desember', 1639.04, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bengkulu', 2018, 'januari', 394.19, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bengkulu', 2018, 'februari', 450.85, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bengkulu', 2018, 'maret', 193, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bengkulu', 2018, 'april', 236.65, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bengkulu', 2018, 'mei', 85.5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bengkulu', 2018, 'juni', 193.8, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bengkulu', 2018, 'juli', 219.75, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bengkulu', 2018, 'agustus', 198.25, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bengkulu', 2018, 'september', 93.5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bengkulu', 2018, 'oktober', 71.85, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bengkulu', 2018, 'november', 233.7, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bengkulu', 2018, 'desember', 258.25, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Lampung', 2018, 'januari', 2345, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Lampung', 2018, 'februari', 1424, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Lampung', 2018, 'maret', 1928, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Lampung', 2018, 'april', 1084.5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Lampung', 2018, 'mei', 941.5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Lampung', 2018, 'juni', 1615, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Lampung', 2018, 'juli', 3080.5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Lampung', 2018, 'agustus', 3122, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Lampung', 2018, 'september', 1847.5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Lampung', 2018, 'oktober', 213, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Lampung', 2018, 'november', 746, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Lampung', 2018, 'desember', 960, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bangka Belitung', 2018, 'januari', 72.1, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bangka Belitung', 2018, 'februari', 54.32, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bangka Belitung', 2018, 'maret', 33.9, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bangka Belitung', 2018, 'april', 42.4, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bangka Belitung', 2018, 'mei', 74.6, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bangka Belitung', 2018, 'juni', 25.5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bangka Belitung', 2018, 'juli', 0.25, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bangka Belitung', 2018, 'agustus', 355.95, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bangka Belitung', 2018, 'september', 13.68, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bangka Belitung', 2018, 'oktober', 49.4, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bangka Belitung', 2018, 'november', 145.5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Bangka Belitung', 2018, 'desember', 5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Kepulauan Riau', 2018, 'januari', 0, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Kepulauan Riau', 2018, 'februari', 0, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Kepulauan Riau', 2018, 'maret', 0, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Kepulauan Riau', 2018, 'april', 0, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Kepulauan Riau', 2018, 'mei', 0, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Kepulauan Riau', 2018, 'juni', 0, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Kepulauan Riau', 2018, 'juli', 0, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Kepulauan Riau', 2018, 'agustus', 0, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Kepulauan Riau', 2018, 'september', 0, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Kepulauan Riau', 2018, 'oktober', 0, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Kepulauan Riau', 2018, 'november', 0, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Kepulauan Riau', 2018, 'desember', 0, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DKI Jakarta', 2018, 'januari', 9, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DKI Jakarta', 2018, 'februari', 15.2, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DKI Jakarta', 2018, 'maret', 15.25, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DKI Jakarta', 2018, 'april', 21.2, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DKI Jakarta', 2018, 'mei', 44.42, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DKI Jakarta', 2018, 'juni', 9.71, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DKI Jakarta', 2018, 'juli', 9, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DKI Jakarta', 2018, 'agustus', 3.33, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DKI Jakarta', 2018, 'september', 13.91, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DKI Jakarta', 2018, 'oktober', 5.01, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DKI Jakarta', 2018, 'november', 19.3, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DKI Jakarta', 2018, 'desember', 8.6, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Barat', 2018, 'januari', 7279.3, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Barat', 2018, 'februari', 6366.5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Barat', 2018, 'maret', 5239.5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Barat', 2018, 'april', 4426, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Barat', 2018, 'mei', 4443, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Barat', 2018, 'juni', 4323, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Barat', 2018, 'juli', 5480, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Barat', 2018, 'agustus', 5069, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Barat', 2018, 'september', 3940.6, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Barat', 2018, 'oktober', 4121.5, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Barat', 2018, 'november', 3381.23, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Barat', 2018, 'desember', 2573.3, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Tengah', 2018, 'januari', 7967.45, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Tengah', 2018, 'februari', 4353.73, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Tengah', 2018, 'maret', 5277.74, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Tengah', 2018, 'april', 4335.39, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Tengah', 2018, 'mei', 5767.59, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Tengah', 2018, 'juni', 4896.55, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Tengah', 2018, 'juli', 8810.18, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Tengah', 2018, 'agustus', 1831.47, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Tengah', 2018, 'september', 1715.83, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Tengah', 2018, 'oktober', 1532.9, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Tengah', 2018, 'november', 1442.01, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Tengah', 2018, 'desember', 2168.05, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DI Yogyakarta', 2018, 'januari', 671.84, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DI Yogyakarta', 2018, 'februari', 1141.95, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DI Yogyakarta', 2018, 'maret', 69.3, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DI Yogyakarta', 2018, 'april', 563.85, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DI Yogyakarta', 2018, 'mei', 829.75, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DI Yogyakarta', 2018, 'juni', 677.85, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DI Yogyakarta', 2018, 'juli', 491.2, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DI Yogyakarta', 2018, 'agustus', 443.75, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DI Yogyakarta', 2018, 'september', 751.2, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DI Yogyakarta', 2018, 'oktober', 491.65, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DI Yogyakarta', 2018, 'november', 339.85, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('DI Yogyakarta', 2018, 'desember', 641.25, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Timur', 2018, 'januari', 5416.04, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Timur', 2018, 'februari', 4924.16, 'padi');
insert into dataset (provinsi, tahun, bulan, jumlah, tanaman) values ('Jawa Timur', 2018, 'maret', 2438.28, 'padi');